stages:
  - lint
  - lab_test
  - deploy

lint:
  stage: lint
  script:
    - ansible-lint playbooks/vlan.yml
    - yamllint vars/vlan_config.yml

lab_test:
  stage: lab_test
  script:
    - ansible-playbook -i inventory/lab_hosts.yml playbooks/vlan.yml
  when: manual

deploy:
  stage: deploy
  script:
    - ansible-playbook -i inventory/prod_hosts.yml playbooks/vlan.yml
  when: manual
  only:
    - main


rollback:
  stage: deploy
  script:
    - ansible-playbook -i inventory/prod_hosts.yml playbooks/vlan_rollback.yml || true
    - ansible-playbook -i inventory/prod_hosts.yml playbooks/acl_rollback.yml || true
  when: manual
  only:
    - main
